### ISSUE TITLE
#lang classicthesis/include doesn't work well with keywords

### ISSUE THREAD

**Issue by takikawa** [stamourv/classicthesis-scribble#4]
For example, the following will error:

```
#lang classicthesis/include

@(require scribble/manual)

Hello my name is @racket[#:test].
```

**Comment by stamourv** [comment]
Oh, weird. Any idea what's going on?

**Comment by takikawa** [comment]
My guess was that `classicthesis/include` expands the contents of the module and maybe the `racket` form isn't bound when it does that (and so it assumes it's a function application that's malformed).

**Comment by stamourv** [comment]
Ah, that's possible. I just checked, and my dissertation doesn't actually use raw keywords inside `racket` forms, which explains why I didn't run into this.
I haven't touched that code in a long time, and can't get to it right now, so do you want to investigate?

**Comment by takikawa** [comment]
Yeah, I'll look into it. I have keywords like that so I'll have to solve it one way or another.
